---
- name: show relevant facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: vigilax
      command: "/usr/local/bin/vigilax.lua"
      register: vigilax_output
    - name: set vigilax
      set_fact:
        vigilax: "{{vigilax_output.stdout}}"
        cacheable: yes
    - name: facts
      debug:
        msg: '{{vigilax | from_json}}'
