---

# backup justfiles and associated files (.env, .aqui)

- name: justfile backup
  hosts: all
  tasks:
    - name: FetchJustfile
      fetch:
        src: "~{{ operator }}/justfile"
        dest: "~/repositories/justfiles/{{ ansible_host }}/justfile"
        flat: yes
    - name: TestAquiExists
      stat:
        path: "~{{ operator }}/.aqui"
      register: aqui_stat
    - name: FetchAqui
      fetch:
        src: "~{{ operator }}/.aqui"
        dest: "~/repositories/justfiles/{{ ansible_host }}/.aqui"
        flat: yes
      when: aqui_stat.stat.exists
    - name: TestEnvExists
      stat:
        path: "~{{ operator }}/.env"
      register: env_stat
    - name: FetchEnv
      fetch:
        src: "~{{ operator }}/.env"
        dest: "~/repositories/justfiles/{{ ansible_host }}/.env"
        flat: yes
      when: env_stat.stat.exists
