---

# backup justfiles and associated files (.env, .aqui)

- name: justfile backup
  hosts: all
  vars:
    dotfiles:
      - "~{{ operator }}/.env"
      - "~{{ operator }}/.aqui"
      - "~{{ operator }}/.workstation"
      - "~{{ operator }}/.ssh/config"

  tasks:
    - name: FetchJustfile
      fetch:
        src: "~{{ operator }}/justfile"
        dest: "~/repositories/justfiles/{{ ansible_host }}/justfile"
        flat: yes
    - name: TestDotfilesExist
      stat:
        path: "{{ item }}"
      register: file_stat
      loop: "{{ dotfiles }}"
    - name: FetchDotFiles
      fetch:
        src: "{{ item.item }}"
        dest: "~/repositories/justfiles/{{ ansible_host }}/{{ item.item | basename }}"
        flat: yes
      when: item.stat.exists
      loop: "{{ file_stat.results }}"
