- name: Patching and Updating Linux Systems
  hosts: all
  become: yes

  tasks:
    - name: Update Arch Linux
      tags: [ archlinux, arch ]
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == 'Archlinux'

    - name: Update Debian-based Systems
      tags: [ debian, ubuntu, deb, ubu ]
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Update RHEL-based Systems
      tags: [ redhat, rh, rhel, centos ]
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Update Alpine-based Systems
      tags: [ alpine, alp ]
      apk:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == 'Alpine'
