---
# This is legacy. 'vigilax.yml' is better, more concise, quicker etc.
# I keep it as it is a nice example of doing the same as 'ansible -t',
# but in a playbook
- name: vigifacts
  hosts: all
  vars:
    cachedir: /dev/shm/lc/vigifacts
  tasks:
    - name: Make sure cachedir exists
      file:
        path: "{{ cachedir }}"
        state: directory
      delegate_to: localhost
      run_once: true
    - name: produce vigilax report
      command: "/usr/local/bin/vigilax"
      register: script_output
    - name: vigilax and facts in combined output
      copy:
        dest: "{{ cachedir }}/{{ inventory_hostname }}"
        content: '{"vigilax":{{ script_output.stdout }},"ansible_facts":{{ansible_facts|to_nice_json}}}'
      delegate_to: localhost
